version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017" # Porta do MongoDB mapeada para a porta local
    volumes:
      - mongo-data:/data/db # Volume para persistência de dados
    restart: always

volumes:
  mongo-data:
    driver: local
